# Generated by Django 4.2.7 on 2026-02-24 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_initial'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_host', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_guest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guest_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('host_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guest_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('host_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released_to_host', 'Released to Host'), ('refunded_to_guest', 'Refunded to Guest'), ('partially_released', 'Partially Released')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('held_until', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf_file', models.FileField(blank=True, upload_to='invoices/')),
                ('pdf_generated', models.BooleanField(default=False)),
                ('sent_to_guest', models.BooleanField(default=False)),
                ('sent_to_host', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_type', models.CharField(choices=[('escrow_release', 'Escrow Release'), ('refund', 'Refund'), ('commission_adjustment', 'Commission Adjustment')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('razorpay_transfer_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('payment.authorized', 'Payment Authorized'), ('payment.failed', 'Payment Failed'), ('payment.captured', 'Payment Captured'), ('refund.created', 'Refund Created'), ('transfer.created', 'Transfer Created'), ('settlement.processed', 'Settlement Processed')], max_length=50)),
                ('razorpay_webhook_id', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('processing', 'Processing')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('booking_payment', 'Booking Payment'), ('deposit', 'Deposit'), ('refund', 'Refund'), ('payout', 'Payout to Host'), ('commission_debit', 'Commission Debit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='payments_tr_user_id_d7ba42_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['booking', 'status'], name='payments_tr_booking_ed032a_idx'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='escrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.escrowaccount'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='host_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_as_guest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_as_host', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionsplit',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_split', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='commissionsplit',
            name='escrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_splits', to='payments.escrowaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='escrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.escrowaccount'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['user', 'status'], name='payments_se_user_id_fb396a_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['user', '-created_at'], name='payments_se_user_id_90863e_idx'),
        ),
    ]
