# Generated by Django 6.0.2 on 2026-02-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rental_days', models.IntegerField()),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_host', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_guest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('guest_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('host_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_use', 'In-Use'), ('returned', 'Returned'), ('disputed', 'Disputed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('escrow_status', models.CharField(choices=[('not_created', 'Not Created'), ('held', 'Held'), ('released_to_host', 'Released to Host'), ('refunded_to_guest', 'Refunded to Guest')], default='not_created', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('handover_at', models.DateTimeField(blank=True, null=True)),
                ('return_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_flag', models.BooleanField(default=False)),
                ('dispute_raised_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('dispute_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_resolution', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingDateLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
