# Generated by Django 4.2.7 on 2026-04-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_loyalty_coins_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
